export type GlossaryCategory = 'P&C' | 'Life' | 'Reinsurance' | 'Legal' | 'General'

export interface GlossaryEntry {
  id: string
  term: string
  koreanName: string
  definition: string
  example: string
  relatedTerms: string[]
  category: GlossaryCategory
  isCustom: boolean
  updatedAt: string
}

export const GLOSSARY_SEED: GlossaryEntry[] = [
  {
    id: 'subrogation',
    term: 'Subrogation',
    koreanName: '대위권',
    definition: '보험자가 피보험자에게 보험금을 지급한 후, 손해를 야기한 제3자에 대해 피보험자의 권리를 대신 행사할 수 있는 법적 권리입니다. 이를 통해 보험자는 과실 있는 제3자로부터 지급한 보험금을 회수할 수 있습니다. 주재원 환경에서는 교통사고, 제품 하자 등 다양한 상황에서 적용됩니다.',
    example: 'After paying a $50,000 claim for vehicle damage caused by a third party, the insurer exercised its right of subrogation to recover the amount from the at-fault driver\'s liability carrier.',
    relatedTerms: ['Indemnity', 'Liability', 'Recovery'],
    category: 'P&C',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'indemnity',
    term: 'Indemnity',
    koreanName: '손해배상 / 손해보상',
    definition: '보험의 기본 원칙으로, 피보험자를 손해 발생 이전의 재무 상태로 복원시키는 것을 의미합니다. 이득을 취하게 해서는 안 된다는 원칙 하에 실제 손해액을 한도로 보상이 이루어집니다. 계약서상 indemnification 조항은 손해 발생 시 상대방 손해를 부담하는 의무를 규정합니다.',
    example: 'The indemnity clause in the contract required the contractor to hold harmless and indemnify the client against any third-party claims arising from the project.',
    relatedTerms: ['Subrogation', 'Liability', 'Hold Harmless'],
    category: 'General',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'deductible',
    term: 'Deductible',
    koreanName: '자기부담금',
    definition: '보험사고 발생 시 피보험자가 자기 부담으로 지출해야 하는 금액으로, 이 금액을 초과하는 손해에 대해 보험자가 보상합니다. 자기부담금이 높을수록 보험료가 낮아지는 구조입니다. 기업 보험에서는 per-occurrence 또는 annual aggregate 기준으로 설정됩니다.',
    example: 'The commercial property policy has a $10,000 deductible per occurrence, meaning the insured must absorb the first $10,000 of each covered loss before the insurer pays.',
    relatedTerms: ['Premium', 'Self-Insured Retention', 'Coinsurance'],
    category: 'P&C',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'reinsurance',
    term: 'Reinsurance',
    koreanName: '재보험',
    definition: '보험회사가 자신이 인수한 위험의 일부를 다른 보험회사(재보험자)에게 전가하는 보험입니다. 원보험자의 손실 변동성을 줄이고 대형 재해에 대한 지급 능력을 확보하는 기능을 합니다. Treaty와 Facultative 방식으로 구분됩니다.',
    example: 'The primary insurer entered into a reinsurance treaty with Munich Re to cede 60% of its catastrophe exposure, thereby protecting its balance sheet from large storm losses.',
    relatedTerms: ['Cession', 'Treaty', 'Retrocession'],
    category: 'Reinsurance',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cession',
    term: 'Cession',
    koreanName: '출재 / 세션',
    definition: '원보험자가 재보험자에게 위험과 그에 상응하는 보험료를 이전하는 행위를 말합니다. 출재 비율(cession rate)에 따라 위험이 분산되며, 재보험자는 비례적으로 손해를 분담합니다. 출재되는 보험료를 ceded premium이라고 합니다.',
    example: 'Under the quota share treaty, the ceding company made a cession of 40% of each risk to the reinsurer, along with the corresponding 40% of the original premium.',
    relatedTerms: ['Reinsurance', 'Treaty', 'Retrocession'],
    category: 'Reinsurance',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'retrocession',
    term: 'Retrocession',
    koreanName: '재재보험 / 레트로세션',
    definition: '재보험자가 자신이 인수한 재보험 위험의 일부를 다시 다른 재보험자에게 전가하는 거래입니다. 재보험 시장 내에서의 위험 분산 메커니즘으로, 대형 재해 시 손실을 업계 전체에 분산시키는 역할을 합니다. 레트로세셔너리는 이러한 위험을 인수하는 재보험자입니다.',
    example: 'Facing excessive catastrophe accumulation, the reinsurer entered into a retrocession agreement to pass 30% of its treaty portfolio to a retrocessionaire.',
    relatedTerms: ['Reinsurance', 'Cession', 'Treaty'],
    category: 'Reinsurance',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'facultative',
    term: 'Facultative',
    koreanName: '임의재보험',
    definition: '재보험의 한 형태로, 재보험자가 개별 위험을 건건이 심사하여 인수 여부를 결정하는 방식입니다. 트리티(특약)와 달리 자동 인수 의무가 없어 대형·특수 위험 처리에 활용됩니다. 원보험자는 필요에 따라 특정 위험에 대해 임의재보험을 요청합니다.',
    example: 'Due to the unusual nature of the offshore drilling platform, the insurer placed facultative reinsurance with three markets to cover the $500 million risk on a case-by-case basis.',
    relatedTerms: ['Treaty', 'Reinsurance', 'Cession'],
    category: 'Reinsurance',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'treaty',
    term: 'Treaty',
    koreanName: '특약재보험',
    definition: '원보험자와 재보험자 간에 일정 기간 동안 특정 포트폴리오 내 모든 위험을 자동으로 인수하기로 사전에 합의한 재보험 계약입니다. 건별 심사 없이 자동 출재·인수가 이루어져 업무 효율성이 높습니다. Quota Share Treaty와 Excess of Loss Treaty가 대표적입니다.',
    example: 'The property treaty automatically covers all risks within the agreed parameters — up to $10 million in value per location — without requiring individual underwriting approval.',
    relatedTerms: ['Facultative', 'Quota Share', 'Excess of Loss'],
    category: 'Reinsurance',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'quota-share',
    term: 'Quota Share',
    koreanName: '비례재보험 / 쿼터쉐어',
    definition: '원보험자가 인수한 모든 위험에 대해 사전에 약정한 일정 비율을 재보험자와 공유하는 방식입니다. 보험료와 손해 모두 동일 비율로 분담되며, 원보험자의 자본 부담을 줄이는 효과가 있습니다. 소규모 보험사나 신설 회사의 능력 확장 수단으로 자주 사용됩니다.',
    example: 'Under a 50% quota share treaty, the insurer cedes half of each premium collected to the reinsurer, which in turn pays 50% of every covered loss.',
    relatedTerms: ['Treaty', 'Excess of Loss', 'Cession'],
    category: 'Reinsurance',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'excess-of-loss',
    term: 'Excess of Loss',
    koreanName: '초과손해재보험 (XL)',
    definition: '재보험의 비비례 방식으로, 원보험자가 일정 금액(retention)을 초과하는 손해에 대해 재보험자가 보상하는 구조입니다. 대형 개별 사고(per risk XL) 또는 연간 누적 손해(aggregate XL)에 적용할 수 있습니다. 보험료 기반 분담이 아닌 손해 발생 기반으로 작동합니다.',
    example: 'The per-risk excess of loss program provides $9 million of coverage above a $1 million retention, so if a single loss reaches $7 million, the reinsurer pays $6 million.',
    relatedTerms: ['Quota Share', 'Treaty', 'Retention'],
    category: 'Reinsurance',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'ibnr',
    term: 'IBNR',
    koreanName: '발생미보고손해 (발생 미보고 보험금)',
    definition: 'Incurred But Not Reported의 약자로, 보험 사고가 이미 발생했지만 아직 보험사에 보고되지 않은 손해에 대한 충당금입니다. 보험사는 과거 경험률을 바탕으로 IBNR을 추정하여 재무제표에 반영해야 합니다. 장기 배상책임 보험에서는 IBNR 규모가 매우 크게 나타납니다.',
    example: 'The actuary estimated $15 million in IBNR reserves for the general liability book, reflecting claims expected to emerge from incidents that occurred before year-end but have not yet been reported.',
    relatedTerms: ['Combined Ratio', 'Underwriting', 'Loss Reserve'],
    category: 'General',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'combined-ratio',
    term: 'Combined Ratio',
    koreanName: '합산비율',
    definition: '손해율(Loss Ratio)과 사업비율(Expense Ratio)을 합산한 비율로, 보험 영업의 수익성을 나타내는 핵심 지표입니다. 100% 이하면 언더라이팅 이익, 100% 초과면 손실을 의미합니다. 미국 손해보험 업계에서 성과를 평가하는 가장 중요한 지표 중 하나입니다.',
    example: 'With a loss ratio of 68% and an expense ratio of 29%, the insurer reported a combined ratio of 97%, indicating a 3% underwriting profit before investment income.',
    relatedTerms: ['IBNR', 'Underwriting', 'Premium'],
    category: 'P&C',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'surplus-lines',
    term: 'Surplus Lines',
    koreanName: '잉여선 보험 / 비인가 시장',
    definition: '주 보험감독청의 허가를 받지 않은 비인가 보험사(non-admitted carrier)가 제공하는 보험으로, 인가 시장에서 인수를 거절당한 고위험 또는 특수 위험을 커버합니다. 별도의 Surplus Lines 브로커를 통해서만 거래가 가능하며, 주별로 규제 체계가 다릅니다. Lloyd\'s of London이 대표적인 서플러스 라인 마켓입니다.',
    example: 'Unable to find coverage in the admitted market for its drone delivery operations, the company secured a $5 million liability policy through a surplus lines broker placing with a non-admitted carrier.',
    relatedTerms: ['Admitted Carrier', 'Underwriting', 'Broker'],
    category: 'Legal',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'admitted-carrier',
    term: 'Admitted Carrier',
    koreanName: '인가 보험사',
    definition: '미국 각 주의 보험감독청으로부터 영업 허가를 받은 보험회사를 의미합니다. 인가 보험사는 주 보증기금(state guaranty fund)의 보호를 받으며, 표준화된 약관과 요율 규제를 따릅니다. 인가를 받지 않은 보험사는 Surplus Lines 시장을 통해서만 위험을 인수할 수 있습니다.',
    example: 'As an admitted carrier in California, the insurer is subject to rate filing requirements and its policyholders are protected by the California Insurance Guarantee Association.',
    relatedTerms: ['Surplus Lines', 'Underwriting', 'Regulatory Compliance'],
    category: 'Legal',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'underwriting',
    term: 'Underwriting',
    koreanName: '언더라이팅 / 위험 심사',
    definition: '보험 인수 여부를 결정하고 적정 보험료를 산출하는 과정으로, 위험의 특성과 크기를 평가합니다. 언더라이터는 손실 이력, 위험 관리 수준, 재무 상태 등을 종합적으로 검토합니다. 적절한 언더라이팅은 보험사의 수익성과 지급 여력 유지에 핵심적인 역할을 합니다.',
    example: 'The underwriter reviewed the applicant\'s five-year loss runs, site inspection report, and financial statements before quoting a premium of $120,000 for the property program.',
    relatedTerms: ['Premium', 'Combined Ratio', 'Admitted Carrier'],
    category: 'General',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'premium',
    term: 'Premium',
    koreanName: '보험료',
    definition: '피보험자가 보험 계약에 의한 보장을 받기 위해 보험자에게 지급하는 대가입니다. 위험의 크기, 보장 범위, 자기부담금 수준 등에 따라 결정되며, 연간 또는 분할 납부가 가능합니다. 재보험 거래에서는 ceded premium(출재 보험료)과 net retained premium(순보유 보험료)으로 구분합니다.',
    example: 'The annual premium for the $10 million directors and officers liability policy was $85,000, representing a rate of $8.50 per $1,000 of limit.',
    relatedTerms: ['Deductible', 'Underwriting', 'Combined Ratio'],
    category: 'General',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'endorsement',
    term: 'Endorsement',
    koreanName: '배서 / 특별약관',
    definition: '보험증권의 기본 약관을 수정하거나 보완하기 위해 추가하는 문서로, rider와 동의어로 사용됩니다. 보장 범위를 확장하거나 제한할 수 있으며, 피보험자 정보 변경 시에도 활용됩니다. 배서는 보험증권의 일부를 구성하며 동등한 법적 효력을 갖습니다.',
    example: 'The company added a pollution liability endorsement to the general liability policy to extend coverage for gradual environmental contamination at the manufacturing facility.',
    relatedTerms: ['Rider', 'Exclusion', 'Policy'],
    category: 'General',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'exclusion',
    term: 'Exclusion',
    koreanName: '면책조항 / 부담보',
    definition: '보험증권에서 보상하지 않는 특정 위험, 손해, 상황을 명시한 조항입니다. 전쟁, 핵위험, 고의적 손해, OFAC 제재 관련 거래 등이 일반적인 면책 사항입니다. 특약을 통해 일부 면책 사항을 다시 담보로 포함시키는 것이 가능합니다.',
    example: 'The policy\'s cyber exclusion bars coverage for any loss arising from unauthorized access to computer systems, a common exclusion in traditional property and liability forms.',
    relatedTerms: ['Endorsement', 'Rider', 'Underwriting'],
    category: 'P&C',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rider',
    term: 'Rider',
    koreanName: '특약 / 추가약관',
    definition: '기본 보험증권에 부가하여 보장 내용을 변경·추가하는 부속 문서로, endorsement와 동의어입니다. 주로 생명보험에서는 rider, 손해보험에서는 endorsement라는 용어를 사용하는 경향이 있습니다. 실무에서 두 용어는 혼용되며 동일한 법적 의미를 갖습니다.',
    example: 'The life insurance policy included a waiver-of-premium rider, ensuring that if the insured became totally disabled, future premiums would be waived without lapsing coverage.',
    relatedTerms: ['Endorsement', 'Exclusion', 'Policy'],
    category: 'Life',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'peril',
    term: 'Peril',
    koreanName: '위험 / 담보위험',
    definition: '손해를 야기할 수 있는 직접적인 원인 또는 사건을 의미합니다. 화재, 폭풍, 도난, 홍수 등이 대표적인 위험(peril)이며, 보험증권은 담보 위험(covered perils) 또는 면책 위험(excluded perils)을 명확히 규정합니다. Named Peril 방식과 All Risk(Open Peril) 방식으로 보장 구조가 나뉩니다.',
    example: 'The named-peril property policy covers damage caused only by the specific perils listed — fire, lightning, windstorm, hail, and explosion — leaving flood and earthquake uninsured.',
    relatedTerms: ['Exclusion', 'Endorsement', 'Underwriting'],
    category: 'P&C',
    isCustom: false,
    updatedAt: '2026-01-01T00:00:00Z',
  },
]
